import 'package:drift/drift.dart';

/// Single-row table (`id == 1`) holding the challenge identity: pairing id,
/// slots, names, start date and the monotonic [stateVersion].
///
/// Owned by the `pairing` feature. See `docs/data-model.md` §2.1 — note that
/// [stateVersion] is written by the `challenge` datasource in the same
/// transaction as each mutation. That cross-feature coupling lives only in the
/// Data layer and is deliberate.
@DataClassName('ChallengeConfigRow')
class ChallengeConfigRows extends Table {
  /// Always `1`: this table holds exactly one row.
  IntColumn get id => integer().withDefault(const Constant(1))();

  /// Logical uint32, generated by whoever creates the challenge.
  IntColumn get pairingId => integer()();

  /// `0` = A, `1` = B.
  IntColumn get localSlot => integer()();

  /// Logical uint64, random per install.
  IntColumn get localInstallId => integer()();

  /// This participant's name, <= 24 UTF-8 bytes.
  TextColumn get localName => text()();

  /// The partner's name; `null` until pairing closes.
  TextColumn get partnerName => text().nullable()();

  /// The partner's install id; `null` until pairing closes.
  IntColumn get partnerInstallId => integer().nullable()();

  /// Days since 1970-01-01 UTC.
  IntColumn get startEpochDay => integer()();

  /// Monotonic counter of local mutations.
  IntColumn get stateVersion => integer().withDefault(const Constant(0))();

  /// Informative only.
  IntColumn get createdAtMillis => integer()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}
